version: "3.9"
services:
    api:
        build: ./api
        ports:
        - "3030:3030"
        depends_on:
          - mongo

    mongo:
      image: "mongo"
      ports:
        - "27017:27017"
      volumes:
        - data:/data/db

volumes:
  data: